### ISSUE TITLE
.yaml in key causes segvault during split

### ISSUE THREAD

**Issue by ptrxyz** [mekkyz/ymlio#7]
```yml
test2.yml:
  int_key2: 2
  string_key2: value2
test3.yaml:
  int_key: 1
  string_key: value
```
Running `ymlio split <file.something>` fails. If `test3.yaml` is replaced with `test3.yml`, then it works.
