### ISSUE TITLE
Indentation is broken when combining files

### ISSUE THREAD

**Issue by ptrxyz** [mekkyz/ymlio#9]
Consider the two files:

```yml
production:
  int_key: 1
  string_key: value
```
```yml
development:
  int_key2: 2
  string_key2: value2
```

running `ymlio combine file1.yml file2.yml output.yml` results in this:

```yml
/tmp/tmp.RJycLxVELk.yml:
  production:
  int_key: 1
  string_key: value

/tmp/tmp.ixXOqTjG5U.yml:
  development:
  int_key2: 2
  string_key2: value2
```

There should be an indentation.
